# Script for Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: $(vmImage)

steps:
- script: |
    echo my vmImage is $(vmImage)

- task: UseDotNet@2
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '8.0.100-rc.2.23502.2'
    includePreviewVersions: true

- script: dotnet --version

- task: NugetToolInstaller@1
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: |
      **/elm-time.csproj
      **/test-elm-time.csproj

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: test
    projects: |
      **/test-elm-time.csproj
    arguments:  --logger trx
    publishTestResults: false

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./implement/elm-time/elm-time.csproj
  displayName: 'publish web host'
