name: test-and-publish

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-18.04, windows-2019]
        include:
          - environment: ubuntu-18.04
            publish-runtime-id: linux-x64
          - environment: windows-2019
            publish-runtime-id: win10-x64

    runs-on: ${{ matrix.environment }}

    steps:
    - name: Avoid git mutating files on checkout
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - name: Try use dotnet core 3
      run: dotnet --info
    - uses: actions/checkout@v1

    - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
      run: dotnet clean ./implement/test-elm-fullstack/test-elm-fullstack.csproj && dotnet nuget locals all --clear

    - name: Run tests with dotnet test
      run: dotnet test ./implement/test-elm-fullstack/test-elm-fullstack.csproj --logger trx
    - name: dotnet publish
      env:
        PUBLISH_RUNTIME_ID: ${{ matrix.publish-runtime-id }}
      run: dotnet publish -c Debug -r ${{ env.PUBLISH_RUNTIME_ID }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true  --output ./publish  ./implement/elm-fullstack
    - name: Publish artifacts
      uses: actions/upload-artifact@v1
      with:
        name: elm-fullstack-bin-${{github.sha}}-${{ matrix.publish-runtime-id }}
        path: ./publish
    - name: dotnet publish with separate assemblies
      run: dotnet publish -c Debug ./implement/elm-fullstack --output ./publish-separate-assemblies
    - name: Publish artifacts with separate assemblies
      uses: actions/upload-artifact@v1
      with:
        name: elm-fullstack-separate-assemblies-${{github.sha}}-${{ matrix.publish-runtime-id }}
        path: ./publish-separate-assemblies
    - name: Elm App Compiler - Run tests with elm-fs elm-test-rs
      run: ./publish/elm-fs  elm-test-rs  ./implement/elm-fullstack/ElmFullstack/compile-elm-program
