name: test-and-publish

on: [push,workflow_dispatch]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-22.04, windows-2022, macos-12]
        include:
          - environment: ubuntu-22.04
            publish-runtime-id: linux-x64
          - environment: windows-2022
            publish-runtime-id: win10-x64
          - environment: macos-12
            publish-runtime-id: osx-x64

    runs-on: ${{ matrix.environment }}

    steps:

    - name: Avoid git mutating files on checkout
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.203'
        include-prerelease: true

    - name: Try use dotnet
      run: dotnet --info

    - name: Clean package cache as a temporary workaround for https://github.com/actions/setup-dotnet/issues/155
      run: dotnet clean ./implement/test-elm-time/test-elm-time.csproj && dotnet nuget locals all --clear

    - name: Run tests with dotnet test
      run: dotnet test ./implement/test-elm-time/test-elm-time.csproj --logger trx

    - name: dotnet publish
      run: dotnet publish -c Debug -r ${{ matrix.publish-runtime-id }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:PublishReadyToRunShowWarnings=true  --output ./publish  ./implement/elm-time

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: elm-time-bin-${{ github.sha }}-${{ matrix.publish-runtime-id }}
        path: ./publish

    - name: dotnet publish with separate assemblies
      run: dotnet publish -c Debug ./implement/elm-time --output ./publish-separate-assemblies

    - name: Publish artifacts with separate assemblies
      uses: actions/upload-artifact@v3
      with:
        name: elm-time-separate-assemblies-${{ github.sha }}-${{ matrix.publish-runtime-id }}
        path: ./publish-separate-assemblies

    - name: Elm App Compiler - Run tests with elm-time elm-test-rs
      # Adapt to elm-test-rs crashing on macOS
      # elm-test-rs also wrote the following before crashing:
      # elm: security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
      if: ${{ !contains( matrix.environment, 'macos') }}
      run: ./publish/elm-time  elm-test-rs  ./implement/elm-time/ElmTime/compile-elm-program
